const PREFIX = '@@redux-traedfri/';

export const GATEWAY_DISCOVERED = `${PREFIX}GATEWAY_DISCOVERED`;
export const SET_CREDENTIALS = `${PREFIX}SET_CREDENTIALS`;
export const CONNECTED = `${PREFIX}CONNECTED`;

export const UPDATE_LIGHT_BULB = `${PREFIX}UPDATE_LIGHT_BULB`;
export const REMOVE_LIGHT_BULB = `${PREFIX}REMOVE_LIGHT_BULB`;
