export const PREFIX = '@@redux-mqtt/';
export const ACTIONABLE = 'actionable/';

export const CLIENT_CONNECTED = `${PREFIX}CLIENT_CONNECTED`;
export const CLIENT_ERROR = `${PREFIX}CLIENT_ERROR`;

export const ADD_SUBSCRIBER = `${PREFIX}${ACTIONABLE}ADD_SUBSCRIBER`;
export const ADDED_SUBSCRIBER = `${PREFIX}ADDED_SUBSCRIBER`;

export const REMOVE_SUBSCRIBER = `${PREFIX}${ACTIONABLE}REMOVE_SUBSCRIBER`;
export const REMOVED_SUBSCRIBER = `${PREFIX}REMOVED_SUBSCRIBER`;

export const PUBLISH = `${PREFIX}${ACTIONABLE}PUBLISH`;
